# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bu alan bo\u015f b\u0131rak\u0131lamaz.', max_length=255)),
                ('price', models.CharField(help_text='Bu alan bo\u015f b\u0131rak\u0131lmaz.', max_length=255)),
                ('image', models.ImageField(upload_to='urunresimleri/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('definition', models.TextField(help_text='\xdcr\xfcn aciklamasini giriniz.', null=True)),
                ('slug', models.SlugField(help_text='Link, otomatik alinir, de\u011fi\u015ftirmeyiniz!!', max_length=80, null=True)),
                ('viewCount', models.IntegerField(default=0)),
            ],
        ),
    ]
