# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bu alan bo\u015f b\u0131rak\u0131lamaz.', max_length=255)),
                ('image', models.ImageField(upload_to='urunresimleri/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(help_text='Link, otomatik alinir, de\u011fi\u015ftirmeyiniz!!', max_length=80, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bu alan bo\u015f b\u0131rak\u0131lamaz.', max_length=255)),
                ('image', models.ImageField(upload_to='urunresimleri/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(help_text='Link, otomatik alinir, de\u011fi\u015ftirmeyiniz!!', max_length=80, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.MainCategory')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
