# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180328_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='urunresimleri/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='urunresimleri/%Y/%m/%d'),
        ),
    ]
